apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: canal-flow

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - auto-agent-ui.yaml
  - service.yaml
  - service-internal.yaml
  - ingress.yaml
