apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

namePrefix: dev-

patches:
  - path: service.yaml
  - path: deployment.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: dev-auto-agent-ui
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: docker-registry.netbase.com/auto-agent-ui-dev
    target:
      kind: Deployment
  - path: ingress.yaml
